INSERT INTO MEMBER(MEM_ID, MEM_PW, MEM_NM, MEM_REGNO, 
                   MEM_NUMBER, MEMBER_ZIP, MEMBER_ADD)
            VALUES('DEMOMEMBER1', 'JAVA', '회원1', '95/01/20',
                   '01047243957', '34939','대전시 중구 중앙로 76 영민빌딩 4층');
INSERT INTO MEMBER(MEM_ID, MEM_PW, MEM_NM, MEM_REGNO, 
                   MEM_NUMBER, MEMBER_ZIP, MEMBER_ADD)
            VALUES('DEMOMEMBER2', 'JAVA', '회원2', '93/11/30',
                   '01010894803', '35232','대전시 서구 둔산로 100');
INSERT INTO MEMBER(MEM_ID, MEM_PW, MEM_NM, MEM_REGNO, 
                   MEM_NUMBER, MEMBER_ZIP, MEMBER_ADD)
            VALUES('DEMOMEMBER3', 'JAVA', '회원3', '99/08/10',
                   '01089014626', '86573','서울시 서초구 서초동 산144-4');
COMMIT;

SELECT  A.ORDER_NO      주문번호,            --주문번호 
        B.BUYER_NAME    가맹점명,            --가맹점명
        F.MENU_NM       메뉴이름,            --메뉴번호
        E.INGR_NAME     재료이름,            --재료이름
        C.INFO_CART_QTY 수량,                --수량
        TO_CHAR(A.ORDER_MEMBER_DATE,'YYYY-MM-DD') 고객주문일,       --고객주문일
        TO_CHAR(A.ORDER_BUYER_CHOICE,'YYYY-MM-DD') 가맹점주문일     --가맹점주문일
FROM ORDERS A   INNER JOIN BUYER B      ON(A.BUYER_ID = B.BUYER_ID)
                INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
                INNER JOIN ADD_INGR D   ON(C.INFO_ORDER_NO = D.INFO_ORDER_NO)
                INNER JOIN INGR E       ON(D.INGR_NO = E.INGR_NO)
                INNER JOIN MENU F       ON(C.MENU_NO_SEQ = F.MENU_NO_SEQ)
WHERE A.MEM_ID = 'DEMOMEMBER1'
AND   A.ORDER_NO = '20210223025937';

SELECT A.ORDER_NO
     , B.BUYER_NAME
     , D.MENU_NM
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
FROM ORDERS A INNER JOIN BUYER B ON(A.BUYER_ID = B.BUYER_ID)
              INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
              INNER JOIN MENU D       ON(C.MENU_NO_SEQ = D.MENU_NO_SEQ);


INSERT INTO CART(CART_NO,MEM_ID,MENU_NO,CART_QTY)
            VALUES(CART_NO_SEQ.NEXTVAL,'DEMOMEMBER1',1,4);
INSERT INTO CART_ADD_INGR(CART_ADD_NO,INGR_NO,CART_NO)
            VALUES(CART_ADD_NO_SEQ.NEXTVAL,'B001',1);
INSERT INTO ORDERS(ORDER_NO, BUYER_ID, MEM_ID, ORDER_MEMBER_DATE )
            VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS'), 'DEMOBUYER1', 'DEMOMEMBER1',SYSDATE);
INSERT INTO INFO_ORDER(INFO_ORDER_NO,MENU_NO_SEQ,ORDER_NO,INFO_CART_QTY)
            VALUES(INFO_ORDER_NO_SEQ.NEXTVAL,1 ,'20210223110950',4);
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'B001');
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'C001');
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'V001');
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'S001');
SELECT A.BUYER_NAME
     , D.MENU_NM
     , F.INGR_NAME
     , C.INFO_CART_QTY || '개'
FROM BUYER A INNER JOIN ORDERS B ON(B.BUYER_ID = A.BUYER_ID)
             INNER JOIN INFO_ORDER C ON(B.ORDER_NO = C.ORDER_NO)
             INNER JOIN MENU D ON(C.MENU_NO_SEQ = D.MENU_NO_SEQ)
             INNER JOIN ADD_INGR E ON(C.INFO_ORDER_NO = E.INFO_ORDER_NO)
             INNER JOIN INGR F ON(E.INGR_NO = F.INGR_NO)
WHERE B.ORDER_NO = '20210223110950'; 
COMMIT;
SELECT A.BUYER_NAME
     , D.MENU_NM
     , C.INFO_CART_QTY || '개'
FROM BUYER A INNER JOIN ORDERS B ON(B.BUYER_ID = A.BUYER_ID)
             INNER JOIN INFO_ORDER C ON(B.ORDER_NO = C.ORDER_NO)
             INNER JOIN MENU D ON(C.MENU_NO_SEQ = D.MENU_NO_SEQ)
             
WHERE B.ORDER_NO = '20210223110950';  

SELECT ORDER_NO
FROM   ORDERS
WHERE  BUYER_ID = 'DEMOBUYER1';

SELECT A.ORDER_NO
     , B.BUYER_NAME
     , D.MENU_NM
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
     , (A.ORDER_PRICE * C.INFO_CART_QTY)
FROM ORDERS A INNER JOIN BUYER B ON(A.BUYER_ID = B.BUYER_ID)
              INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
              INNER JOIN MENU D       ON(C.MENU_NO_SEQ = D.MENU_NO_SEQ)
WHERE A.MEM_ID = 'DEMOMEMBER1'
ORDER BY A.ORDER_NO;
              
SELECT A.ORDER_NO      
     , B.BUYER_NAME    
     , F.MENU_NM       
     , E.INGR_NAME     
     , C.INFO_CART_QTY 
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
     , TO_CHAR(A.ORDER_BUYER_CHOICE,'YY-MM-DD')
FROM ORDERS A   INNER JOIN BUYER B      ON(A.BUYER_ID = B.BUYER_ID)
                INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
                INNER JOIN ADD_INGR D   ON(C.INFO_ORDER_NO = D.INFO_ORDER_NO)
                INNER JOIN INGR E       ON(D.INGR_NO = E.INGR_NO)
                INNER JOIN MENU F       ON(C.MENU_NO = F.MENU_NO)
;--WHERE A.ORDER_NO = '20210223051839';

SELECT A.ORDER_NO
     , B.BUYER_NAME
     , D.MENU_NM
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
FROM ORDERS A INNER JOIN BUYER B ON(A.BUYER_ID = B.BUYER_ID)
              INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
              INNER JOIN MENU D       ON(C.MENU_NO_SEQ = D.MENU_NO_SEQ)
WHERE A.ORDER_BUYER_CHOICE IS NULL
AND   B.BUYER_ID = 'DEMOBUYER1';

--샌드위치, 샐러드 조회
SELECT A.ORDER_NO      
     , B.BUYER_NAME    
     , F.MENU_NM       
     , E.INGR_NAME     
     , C.INFO_CART_QTY 
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
     , TO_CHAR(A.ORDER_BUYER_CHOICE,'YY-MM-DD')
     , (A.ORDER_PRICE * C.INFO_CART_QTY)
FROM ORDERS A   INNER JOIN BUYER B      ON(A.BUYER_ID = B.BUYER_ID)
                INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
                INNER JOIN ADD_INGR D   ON(C.INFO_ORDER_NO = D.INFO_ORDER_NO)
                INNER JOIN INGR E       ON(D.INGR_NO = E.INGR_NO)
                INNER JOIN MENU F       ON(C.MENU_NO = F.MENU_NO)
WHERE A.ORDER_NO = '20210224080033' --다른거 : 20210224080033, 랩: 20210224080223
AND   A.MEM_ID = 'DEMOMEMBER1';
--랩조회
SELECT A.ORDER_NO      
     , B.BUYER_NAME    
     , F.MENU_NM   
     , C.INFO_CART_QTY 
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
     , TO_CHAR(A.ORDER_BUYER_CHOICE,'YY-MM-DD')
     , (A.ORDER_PRICE * C.INFO_CART_QTY)
FROM ORDERS A   INNER JOIN BUYER B      ON(A.BUYER_ID = B.BUYER_ID)
                INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
                INNER JOIN MENU F       ON(C.MENU_NO = F.MENU_NO)
WHERE A.ORDER_NO = '20210224080223'
AND   A.MEM_ID = 'DEMOMEMBER1';

--MENU_GU 랩
SELECT A.ORDER_NO      
     , F.MENU_GU   
FROM ORDERS A   INNER JOIN INFO_ORDER C       ON(A.ORDER_NO = C.ORDER_NO)
                INNER JOIN MENU F       ON(C.MENU_NO = F.MENU_NO)
WHERE A.ORDER_NO = '20210224080223'
AND   A.MEM_ID = 'DEMOMEMBER1';

----


UPDATE ORDERS
SET    ORDER_BUYER_CHOICE = SYSDATE
WHERE  ORDER_NO = '20210223063329';

SELECT A.ORDER_NO
     , B.BUYER_NAME
     , C.INFO_CART_QTY
FROM   ORDERS A LEFT OUTER JOIN BUYER B ON(A.BUYER_ID = B.BUYER_ID)
                LEFT OUTER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO);
        
SELECT ORDER_NO
FROM ORDERS 
WHERE BUYER_ID = 'DEMOBUYER1'
ORDER BY ORDER_NO;

SELECT A.ORDER_NO
     , C.INFO_ORDER_NO
     , B.BUYER_NAME
     , D.MENU_NM 
     , TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD')
     , TO_CHAR(A.ORDER_BUYER_CHOICE,'YY-MM-DD')
     , A.ORDER_PRICE
FROM ORDERS A INNER JOIN BUYER B ON(A.BUYER_ID = B.BUYER_ID)
              INNER JOIN INFO_ORDER C ON(A.ORDER_NO = C.ORDER_NO)
              INNER JOIN MENU D       ON(C.MENU_NO = D.MENU_NO)
WHERE B.BUYER_ID = 'DEMOBUYER1';


DELETE FROM ORDERS 
WHERE  ORDER_NO = '20210224121949';

DELETE FROM ADD_INGR
WHERE  INFO_ORDER_NO = '27';

DELETE FROM INFO_ORDER
WHERE INFO_ORDER_NO = '27';

INSERT INTO CART(CART_NO, MEM_ID, MENU_NO, CART_QTY)
            VALUES(CART_NO_SEQ.NEXTVAL, 'DEMOMEMBER1',1, 1);
INSERT INTO CART_ADD_INGR(CART_ADD_NO, INGR_NO, CART_NO)
            VALUES(CART_ADD_NO_SEQ.NEXTVAL, '선택재료', 'cartNo');
INSERT INTO CART_ADD_INGR(CART_ADD_NO, INGR_NO, CART_NO)
            VALUES(CART_ADD_NO_SEQ.NEXTVAL, '선택재료', 'cartNo');
INSERT INTO CART_ADD_INGR(CART_ADD_NO, INGR_NO, CART_NO)
            VALUES(CART_ADD_NO_SEQ.NEXTVAL, '선택재료', 'cartNo');
INSERT INTO CART_ADD_INGR(CART_ADD_NO, INGR_NO, CART_NO)
            VALUES(CART_ADD_NO_SEQ.NEXTVAL, '선택재료', 'cartNo');
commit;
SELECT CART_NO
FROM   CART
WHERE  MEM_ID = 'DEMOMEMBER1'
ORDER BY CART_NO;

INSERT INTO ORDERS(ORDER_NO, BUYER_ID, MEM_ID, ORDER_MEMBER_DATE )
            VALUES(TO_CHAR(SYSDATE,'YYYYMMDDHHMISS'), 'DEMOBUYER1', 'DEMOMEMBER1',SYSDATE);
INSERT INTO INFO_ORDER(INFO_ORDER_NO,MENU_NO_SEQ,ORDER_NO,INFO_CART_QTY)
            VALUES(INFO_ORDER_NO_SEQ.NEXTVAL,1 ,'20210223110950',4);
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'B001');
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'C001');
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'V001');
INSERT INTO ADD_INGR(ADD_INGR_NO,INFO_ORDER_NO,INGR_NO)
            VALUES(ADD_INGR_NO_SEQ.NEXTVAL,2,'S001');
            
            
SELECT CART_NO,MEM_ID,MENU_NO,CART_QTY 
FROM   CART WHERE MEM_ID = 'DEMOMEMBER1';

SELECT INFO_ORDER_NO,MENU_NO,ORDER_NO,INFO_CART_QTY 
FROM   INFO_ORDER
WHERE  ORDER_NO = (SELECT MAX(ORDER_NO) FROM INFO_ORDER);

--주문정보 테이블에 데이터 입력
INSERT INTO INFO_ORDER(INFO_ORDER_NO,MENU_NO,ORDER_NO,INFO_CART_QTY)
SELECT INFO_ORDER_NO_SEQ.NEXTVAL,MENU_NO,(SELECT MAX(ORDER_NO) FROM ORDERS), CART_QTY
FROM   CART WHERE MEM_ID = 'DEMOMEMBER1';--카트테이블

SELECT * FROM CART_ADD_INGR;

INSERT INTO ADD_INGR(ADD_INGR_NO, INFO_ORDER_NO, INGR_NO)
SELECT ADD_INGR_NO_SEQ.NEXTVAL, (SELECT MAX(INFO_ORDER_NO) FROM INFO_ORDER), INGR_NO
FROM   CART_ADD_INGR A WHERE A.CART_NO = (SELECT B.CART_NO FROM CART B WHERE B.CART_NO = A.CART_NO);
--카트에드 테이블
UPDATE ORDERS
SET    ORDER_PRICE = 4800
WHERE  ORDER_NO = '20210224060942';

DELETE FROM CART_ADD_INGR;
DELETE FROM CART;
commit;


--최종 고객 주문등록 출력리스트
SELECT  A.ORDER_NO ,
C.MENU_NO 메뉴분류코드,
B.BUYER_NAME ,  
F.MENU_NM ,  
E.INGR_NAME,  
C.INFO_CART_QTY ,
TO_CHAR(A.ORDER_MEMBER_DATE,'YY-MM-DD'),
TO_CHAR(A.ORDER_BUYER_CHOICE,'YY-MM-DD'),
A.ORDER_PRICE 
FROM ORDERS A   INNER JOIN BUYER B      ON(A.BUYER_ID = B.BUYER_ID) 
INNER JOIN INFO_ORDER C                 ON(A.ORDER_NO = C.ORDER_NO) 
INNER JOIN ADD_INGR D                   ON(C.INFO_ORDER_NO = D.INFO_ORDER_NO) 
INNER JOIN INGR E                       ON(D.INGR_NO = E.INGR_NO)  
INNER JOIN MENU F                       ON(C.MENU_NO = F.MENU_NO) 
WHERE A.MEM_ID = 'DEMOMEMBER1' AND   
A.ORDER_NO = '20210224090824';